>L36092|TRBV10-1*01|Homo sapiens|F|V-REGION|214801..215087|287 nt|1| | | | |287+0=287| | |
gctacagtgtctctagatcaaacacagaggacctccccctcactctggagtctgctgcct
cctcccagacatctgtatatttctgcgccagcagtgagtc
>AF009660|TRBV10-1*02|Homo sapiens|F|V-REGION|54913..55199|287 nt|1| | || |287+0=287| | |
gctacagtgtctctagatcaaacacagaggacctccccctcactctggagtctgctgcct
cctcccagacatctgtatatttctgcgccagcagtgagtc
>L36092|TRBV10-2*01|Homo sapiens|F|V-REGION|239867..240153|287 nt|1| | | | |287+0=287| | |
gctatgttgtctccagatccaagacagagaatttccccctcactctggagtcagctaccc
gctcccagacatctgtgtatttctgcgccagcagtgagtc
>U17048|TRBV10-2*02|Homo sapiens|[F]|V-REGION|1..217|217 nt|1| | | | |217+0=217|partial in 5'| |
agataaaggagaagtccccgatggctacgttgtctccagatccaagacagagaatttccc
cctcactctggagtcagctacccgctcccagacatctgtg
>U03115|TRBV10-3*01|Homo sapiens|F|V-REGION|14880..15166|287 nt|1| | | | |287+0=287| | |
gctatagtgtctctagatcaaagacagaggatttcctcctcactctggagtccgctacca
gctcccagacatctgtgtacttctgtgccatcagtgagtc
>U17047|TRBV10-3*02|Homo sapiens|F|V-REGION|81..367|287 nt|1| | | | |287+0=287| | |
gctatagtgtctctagatcaaagacagaggatttcctcctcactctggagtccgctacca
gctcccagacatctgtgtacttctgtgccatcagtgagtc
>L33101|TRBV10-3*03|Homo sapiens|[F]|V-REGION|1..273|273 nt|1| | | | |273+0=273| | |
agaagtctcagatggctatagtgtctctagatcaaagacagaggatttcctcctcactct
ggagtccgctaccagctcccagacatctgtgtacttctgt
>L33102|TRBV10-3*04|Homo sapiens|[F]|V-REGION|1..273|273 nt|1| | | | |273+0=273| | |
agaagtctcagatggctatagtgtctctagatcaaagacagaggatttcctcctcactct
ggagtccgctaccagctcccagacatctgtgtacttctgt
>M33233|TRBV11-1*01|Homo sapiens|F|V-REGION|747..1036|290 nt|1| | | | |290+0=290| | |
gattttctgcagagaggctcaaaggagtagactccactctcaagatccagcctgcagagc
ttggggactcggccatgtatctctgtgccagcagcttagc
>L36092|TRBV11-2*01|Homo sapiens|F|V-REGION|248813..249102|290 nt|1| | | | |290+0=290| | |
gattttctgcagagaggctcaaaggagtagactccactctcaagatccagcctgcaaagc
ttgaggactcggccgtgtatctctgtgccagcagcttaga
>M33235|TRBV11-2*02|Homo sapiens|[F]|V-REGION|171..455|285 nt|1| | | | |285+0=285| | |
ggatcgattttctgcagagaggctcaaaggagtagactccactctcaagatccagcctgc
aaagcttgagaactcggccgtgtatctctgtgccagcagt
>X58796|TRBV11-2*03|Homo sapiens|(F)|V-REGION|81..365|285 nt|1| | | | |285+0=285| | |
ggatcgattttctgcagagaggctcaaaggagtagactccactctcaagatccaacctgc
aaagcttgaggactcggccgtgtatctctgtgccagcagc
>U03115|TRBV11-3*01|Homo sapiens|F|V-REGION|25513..25802|290 nt|1| | | | |290+0=290| | |
gattttctgcagagaggctcaaaggagtagactccactctcaagatccagcctgcagagc
ttggggactcggccgtgtatctctgtgccagcagcttaga
>X58797|TRBV11-3*02|Homo sapiens|(F)|V-REGION|103..387|285 nt|1| | | | |285+0=285| | |
ggatcgattttctgcagagaggctcaaaggagtagactccactctcaagatccagcctgc
agagcttggggactcggccgtgtatctctgtgccagcagc
>M62377|TRBV11-3*03|Homo sapiens|(F)|V-REGION|1..269|269 nt|1| | | | |269+0=269|partial in 5'| |
ggatcgattttctgcagagaggctcaaaggagtagactccactctcaagatccagccagc
agagcttggggactcggccatgtatctctgtgccagcagc
>X07192|TRBV12-3*01|Homo sapiens|F|V-REGION|426..715|290 nt|1| | | | |290+0=290| | |
gattctcagctaagatgcctaatgcatcattctccactctgaagatccagccctcagaac
ccagggactcagctgtgtacttctgtgccagcagtttagc
>K02546|TRBV12-4*01|Homo sapiens|F|V-REGION|158..447|290 nt|1| | | | |290+0=290| | |
gattctcagctaagatgcctaatgcatcattctccactctgaagatccagccctcagaac
ccagggactcagctgtgtacttctgtgccagcagtttagc
>M14264|TRBV12-4*02|Homo sapiens|(F)|V-REGION|58..345|288 nt|1| | | | |288+0=288| | |
tcgattctcagctaagatgcctaatgcatcattctccactctgaggatccagccctcaga
acccagggactcagctgtgtacttctgtgccagcagttta
>X07223|TRBV12-5*01|Homo sapiens|F|V-REGION|392..681|290 nt|1| | | | |290+0=290| | |
gattctcagcagagatgcctgatgcaactttagccactctgaagatccagccctcagaac
ccagggactcagctgtgtatttttgtgctagtggtttggt
>U03115|TRBV13*01|Homo sapiens|F|V-REGION|6502..6788|287 nt|1| | | | |287+0=287| | |
gattctcagctcaacagttcagtgactatcattctgaactgaacatgagctccttggagc
tgggggactcagccctgtacttctgtgccagcagcttagg
>M62378|TRBV13*02|Homo sapiens|(F)|V-REGION|128..409|282 nt|1| | | | |282+0=282| | |
tgatcgattctcagctcaacagttcagtgactatcattctgaactgaacatgagctcctt
ggagctgggggactcagccctgtacttctgtgccagcagc
>X06154|TRBV14*01|Homo sapiens|F|V-REGION|283..572|290 nt|1| | | | |290+0=290| | |
gattcttagctgaaaggactggagggacgtattctactctgaaggtgcagcctgcagaac
tggaggattctggagtttatttctgtgccagcagccaaga
>X57722|TRBV14*02|Homo sapiens|(F)|V-REGION|46..330|285 nt|1| | | | |285+0=285| | |
caatcgattcttagctgaaaggactggagggacgtattctactctgaaggtgcagcctgc
agaactggaggattctggagtttatttctgtgccagcagc
>U03115|TRBV15*01|Homo sapiens|F|V-REGION|63681..63967|287 nt|1| | | | |287+0=287| | |
acttccaatccaggaggccgaacacttctttctgctttcttgacatccgctcaccaggcc
tgggggacacagccatgtacctgtgtgccaccagcagaga
>X58800|TRBV15*02|Homo sapiens|(F)|V-REGION|85..366|282 nt|1| | | | |282+0=282| | |
tgataacttccaatccaggaggccgaacacttctttctgctttcttgacatccgctcacc
aggcctgggggacgcagccatgtacctgtgtgccaccagc
>M62376|TRBV15*03|Homo sapiens|(F)|V-REGION|135..416|282 nt|1| | | | |282+0=282| | |
tgataacttccaatccaggaggccgaacacttctttctgctttctagacatccgctcacc
aggcctgggggacgcagccatgtaccagtgtgccaccagc
>L26231|TRBV16*01|Homo sapiens|F|V-REGION|419..708|290 nt|1| | | | |290+0=290| | |
gattttcagctaagtgcctcccaaattcaccctgtagccttgagatccaggctacgaagc
ttgaggattcagcagtgtatttttgtgccagcagccaatc
>L26054|TRBV16*03|Homo sapiens|(F)|V-REGION|58..342|285 nt|1| | | | |285+0=285| | |
ggaaagattttcagctaagtgcctcccaaattcaccctgtagccttgagatccaggctac
gaagcttgaggattcagcagtgtatttttgtgccagcagc
>U03115|TRBV17*01|Homo sapiens|ORF|V-REGION|72572..72858|287 nt|1| | | | |287+0=287| | |
aacgattcacagctgaaagacctaacggaacgtcttccacgctgaagatccatcccgcag
agccgagggactcagccgtgtatctctacagtagcggtgg
>L36092|TRBV18*01|Homo sapiens|F|V-REGION|450875..451164|290 nt|1| | | | |290+0=290| | |
gattttctgctgaatttcccaaagagggccccagcatcctgaggatccagcaggtagtgc
gaggagattcggcagcttatttctgtgccagctcaccacc
>L36092|TRBV19*01|Homo sapiens|F|V-REGION|453995..454281|287 nt|1| | | | |287+0=287| | |
ggtacagcgtctctcgggagaagaaggaatcctttcctctcactgtgacatcggcccaaa
agaacccgacagctttctatctctgtgccagtagtataga
>U48259|TRBV19*02|Homo sapiens|F|V-REGION|239..525|287 nt|1| | | | |287+0=287| | |
ggtacagcgtctctcgggagaagaaggaatcctttcctctcactgtgacatcggcccaaa
agaacccgacagctttctatctctgtgccagtagtataga
>M97725|TRBV19*03|Homo sapiens|(F)|V-REGION|58..338|281 nt|1| | || |281+0=281| | |
ctgaagggtacagcgtctctcgggagaagaaggaatcctttcctctcactgtgacatcgg
cccaaaagaacccgacagctttctatctctgtgccagtag
>L36092|TRBV2*01|Homo sapiens|F|V-REGION|93697..93986|290 nt|1| | | | |290+0=290| | |
aattctcagttgaaaggcctgatggatcaaatttcactctgaagatccggtccacaaagc
tggaggactcagccatgtacttctgtgccagcagtgaagc
>M62379|TRBV2*02|Homo sapiens|(F)|V-REGION|1..285|285 nt|1| | | | |285+0=285| | |
tgatcaattctcagttgaaaggcctgatggatcaaatttcactctgaagatccggtccac
aaagctggaggactcagccatgtacttctgtgccagcagt
>M64351|TRBV2*03|Homo sapiens|(F)|V-REGION|82..369|288 nt|1| | | | |288+0=288| | |
tcaattctcagttgagaggcctgatggatcaaatttcactctgaagatccggtccacaaa
gctggaggactcagccatgtacttctgtgccagcagtgaa
>M11955|TRBV20-1*01|Homo sapiens|F|V-REGION|427..719|293 nt|1| | | | |293+0=293| | |
acaagtttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgccc
atcctgaagacagcagcttctacatctgcagtgctagaga
>X72719|TRBV20-1*02|Homo sapiens|F|V-REGION|381..668|288 nt|1| | | | |288+0=288| | |
gaaggacaagtttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccag
tgcccatcctgaagacagcagcttctacatctgcagtgct
>M11954|TRBV20-1*03|Homo sapiens|(F)|V-REGION|427..714|288 nt|1| | | | |288+0=288| | |
gaaggacaagtttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccag
tgcccatcctgaagacagcagcttctacatctgcagtgct
>M14263|TRBV20-1*04|Homo sapiens|(F)|V-REGION|46..336|291 nt|1| | | | |291+0=291| | |
ggacaagtttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgc
ccatcctgaagacagcagcttctacatctgcagtgctagt
>X57604|TRBV20-1*05|Homo sapiens|(F)|V-REGION|396..686|291 nt|1| | | | |291+0=291| | |
ggacaagtttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgc
ccatcctgaagacagcagcttctacatctgcagtgctaga
>D13088|TRBV20-1*06|Homo sapiens|(F)|V-REGION|43..330|288 nt|1| | | | |288+0=288| | |
gaaggacaagtttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccag
tgcccatcctgaagacagcagcttctacatctgcagtgct
>X74852|TRBV20-1*07|Homo sapiens|(F)|V-REGION|64..354|291 nt|1| | | | |291+0=291| | |
ggacaagtttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgc
ccatcctgaagacagcagcttctacatctgcagtgctaga
>L36092|TRBV23-1*01|Homo sapiens|ORF|V-REGION|480906..481195|290 nt|1| | | | |290+0=290| | |
gattctcatctcaatgccccaagaacgcaccctgcagcctggcaatcctgtcctcagaac
cgggagacacggcactgtatctctgcgccagcagtcaatc
>M11951|TRBV24-1*01|Homo sapiens|F|V-REGION|189..476|288 nt|1| | | | |288+0=288| | |
atacagtgtctctcgacaggcacaggctaaattctccctgtccctagagtctgccatccc
caaccagacagctctttacttctgtgccaccagtgatttg
>L36092|TRBV25-1*01|Homo sapiens|F|V-REGION|504596..504882|287 nt|1| | | | |287+0=287| | |
agtcaacagtctccagaataaggacggagcattttcccctgaccctggagtctgccaggc
cctcacatacctctcagtacctctgtgccagcagtgaata
>L36092|TRBV26*01|Homo sapiens|P|V-REGION|529534..529820|287 nt|1| | | | |287+0=287| | |
ggtatcatgtttcttgaaatactatagcatcttttcccctgaccctgaagtctgccagca
ccaaccagacatctgtgtatctctatgccagcagttcatc
>L36092|TRBV27*01|Homo sapiens|F|V-REGION|549224..549510|287 nt|1| | | | |287+0=287| | |
ggtacaaagtctctcgaaaagagaagaggaatttccccctgatcctggagtcgcccagcc
ccaaccagacctctctgtacttctgtgccagcagtttatc
>U08314|TRBV28*01|Homo sapiens|F|V-REGION|408..694|287 nt|1| | | | |287+0=287| | |
ggtacagtgtctctagagagaagaaggagcgcttctccctgattctggagtccgccagca
ccaaccagacatctatgtacctctgtgccagcagtttatg
>L36092|TRBV29-1*01|Homo sapiens|F|V-REGION|574270..574559|290 nt|1| | | | |290+0=290| | |
acaagtttcccatcagccgcccaaacctaacattctcaactctgactgtgagcaacatga
gccctgaagacagcagcatatatctctgcagcgttgaaga
>M13847|TRBV29-1*02|Homo sapiens|(F)|V-REGION|17..304|288 nt|1| | | | |288+0=288| | |
tgacaagtttcccatcagccgcccaaacctaacattctcaagtctgactgtgagcaacat
gagccctgaagacagcagcatatatctctgcagcgttgaa
>X04926|TRBV29-1*03|Homo sapiens|(F)|V-REGION|1..231|231 nt|1| | | | |231+0=231|partial in 5'| |
tgacaagtttcccatcagccgcccaaacctaacattctcaactctgactgtgagcaacat
gagccctgaagacagcagcatatatctctgcagcgcgggc
>U07977|TRBV3-1*01|Homo sapiens|F|V-REGION|5648..5934|287 nt|1| | | | |287+0=287| | |
gcttctcacctaaatctccagacaaagctcacttaaatcttcacatcaattccctggagc
ttggtgactctgctgtgtatttctgtgccagcagccaaga
>L06889|TRBV3-1*02|Homo sapiens|(F)|V-REGION|58..336|279 nt|1| | | | |279+0=279| | |
tccaaatcgattctcacctaaatctccagacaaagctaaattaaatcttcacatcaattc
cctggagcttggtgactctgctgtgtatttctgtgccagc
>L36092|TRBV30*01|Homo sapiens|F|V-REGION|666640..666923|284 nt|1| | | | |284+0=284| | |
agaatctctcagcctccagaccccaggaccggcagttcatcctgagttctaagaagctcc
ttctcagtgactctggcttctatctctgtgcctggagtgt
>Z13967|TRBV30*02|Homo sapiens|F|V-REGION|416..699|284 nt|1| | | | |284+0=284| | |
agaatctctcagcctccagaccccaggaccggcagttcatcctgagttctaagaagctcc
tcctcagtgactctggcttctatctctgtgcctggagtgt
>M13554|TRBV30*04|Homo sapiens|(F)|V-REGION|1..276|276 nt|1| | | | |276+0=276| | |
ccagaatctctcagcctccagaccccaggaccggcagttcattctgagttctaagaagct
cctcctcagtgactctggcttctatctctgtgcctggagt
>L06893|TRBV30*05|Homo sapiens|(F)|V-REGION|52..333|282 nt|1| | | | |282+0=282| | |
ccagaatctctcagcctccagaccccaggaccggcagttcatcctgagttctaagaagct
ccttctcagtgactctggcttctatctctgtgcctgggga
>U07977|TRBV4-1*01|Homo sapiens|F|V-REGION|10268..10554|287 nt|1| | | | |287+0=287| | |
gcttctcacctgaatgccccaacagctctctcttaaaccttcacctacacgccctgcagc
cagaagactcagccctgtatctctgcgccagcagccaaga
>M13855|TRBV4-1*02|Homo sapiens|(F)|V-REGION|1..259|259 nt|1| | || |259+0=259|partial in 5'| |
cgcttctcacctgaatgccccaacagctctctcttaaaccttcacctacacgccctgcag
ccagaagactcagccctgtatctctgcgccagcagccaag
>U07975|TRBV4-2*01|Homo sapiens|F|V-REGION|477..763|287 nt|1| | | | |287+0=287| | |
gcttctcacctgaatgccccaacagctctcacttattccttcacctacacaccctgcagc
cagaagactcggccctgtatctctgtgccagcagccaaga
>X58811|TRBV4-2*02|Homo sapiens|(F)|V-REGION|169..450|282 nt|1| | | | |282+0=282| | |
aagtcgcttctcacctgaatgccccaacagctctcacttatgccttcacctacacaccct
gcagccagaagactcggccctgtatctctgtgccagcacc
>U07978|TRBV4-3*01|Homo sapiens|F|V-REGION|20940..21226|287 nt|1| | | | |287+0=287| | |
gcttctcacctgaatgccccaacagctctcacttattccttcacctacacaccctgcagc
cagaagactcggccctgtatctctgcgccagcagccaaga
>X58812|TRBV4-3*02|Homo sapiens|(F)|V-REGION|73..354|282 nt|1| | | | |282+0=282| | |
aagtcgcttctcacctgaatgccccaacagctctcacttatcccttcacctacacaccct
gcagccagaagactcggccctgtatctctgcgccagcagc
>L06888|TRBV4-3*03|Homo sapiens|(F)|V-REGION|58..339|282 nt|1| | | | |282+0=282| | |
aagtcgcttctcacctgaatgccccaacagctctcacttattccttcacctacacaccct
gcagccagaagactcggccctgtatctctgcgccagcagc
>X57616|TRBV4-3*04|Homo sapiens|(F)|V-REGION|1..231|231 nt|1| | | | |231+0=231|partial in 5'| |
aagtcgcttctcacctgaatgccccaacagctctcacttattccttcacctacacaccct
gcagccagaagactcggccctgtatctctgcgccagcagc
>L36092|TRBV5-1*01|Homo sapiens|F|V-REGION|113806..114091|286 nt|1| | | | |286+0=286| | |
cgattctcagggcgccagttctctaactctcgctctgagatgaatgtgagcaccttggag
ctgggggactcggccctttatctttgcgccagcagcttgg
>M14271|TRBV5-1*02|Homo sapiens|(F)|V-REGION|50..328|279 nt|1| | || |279+0=279| | |
ccttggtcgattctcagggcgccagttctctaactctcgctctgagatgaatgtgagcac
cttggagctgggggactcggccctttatctttgcgccagc
>X61439|TRBV5-3*01|Homo sapiens|ORF|V-REGION|417..702|286 nt|1| | | | |286+0=286| | |
cgattctcagggcgccagttccatgactgttgctctgagatgaatgtgagtgccttggag
ctgggggactcggccctgtatctctgtgccagaagcttgg
>AF009660|TRBV5-3*02|Homo sapiens|ORF|V-REGION|44205..44490|286 nt|1| | | | |286+0=286| | |
cgattctcagggcgccagttccatgactattgctctgagatgaatgtgagtgccttggag
ctgggggactcggccctgtatctctgtgccagaagcttgg
>L36092|TRBV5-4*01|Homo sapiens|F|V-REGION|278005..278290|286 nt|1| | | | |286+0=286| | |
agattctcaggtctccagttccctaattatagctctgagctgaatgtgaacgccttggag
ctggacgactcggccctgtatctctgtgccagcagcttgg
>X57615|TRBV5-4*02|Homo sapiens|(F)|V-REGION|65..346|282 nt|1| | | | |282+0=282| | |
tcctagattctcaggtctccagttccctaattataactctgagctgaatgtgaacgcctt
ggagctggacgactcggccctgtatctctgtgccagcagc
>S50547|TRBV5-4*03|Homo sapiens|(F)|V-REGION|1..234|234 nt|1| | | | |234+0=234|partial in 5'| |
tcctagattctcaggtctccagttccctaattatagctctgagctgaatgtgaacgcctt
ggagctggacgactcggccctgtatctctgtgccagcagc
>X58804|TRBV5-4*04|Homo sapiens|(F)|V-REGION|1..192|192 nt|1| | | | |192+0=192|partial in 5'| |
tcctagattctcaggtctccagttccctaattatagctctgagctgaatgtgaacgcctt
ggagctggacgactcggccctgtatctctgtgccagcagc
>L36092|TRBV5-5*01|Homo sapiens|F|V-REGION|297450..297735|286 nt|1| | | | |286+0=286| | |
cgattctcagctcgccagttccctaactatagctctgagctgaatgtgaacgccttgttg
ctgggggactcggccctgtatctctgtgccagcagcttgg
>X57611|TRBV5-5*02|Homo sapiens|(F)|V-REGION|65..346|282 nt|1| | | | |282+0=282| | |
tgatcgattctcagctcgccagttccctaactatagctctgagctgaatgtgaacgcctt
gttgctgggggactcggccctgtatctctgtgccagcagc
>X58801|TRBV5-5*03|Homo sapiens|(F)|V-REGION|129..410|282 nt|1| | | | |282+0=282| | |
tgatcgattctcagctcgccagttccctaactatagctctgagctgaatgtgaacgcctt
gttgctgggggactcggccctgtatctctgtgccagcagc
>L36092|TRBV5-6*01|Homo sapiens|F|V-REGION|314963..315248|286 nt|1| | | | |286+0=286| | |
cgattctcaggtcaccagttccctaactatagctctgagctgaatgtgaacgccttgttg
ctgggggactcggccctctatctctgtgccagcagcttgg
>L36092|TRBV5-7*01|Homo sapiens|ORF|V-REGION|334981..335266|286 nt|1| | | | |286+0=286| | |
caattctcaggtcaccagttccctaactatagctctgagctgaatgtgaacgccttgttg
ctaggggactcggccctctatctctgtgccagcagcttgg
>L36092|TRBV5-8*01|Homo sapiens|F|V-REGION|355117..355402|286 nt|1| | | | |286+0=286| | |
agattttcaggtcgccagttccctaattatagctctgagctgaatgtgaacgccttggag
ctggaggactcggccctgtatctctgtgccagcagcttgg
>X58803|TRBV5-8*02|Homo sapiens|(F)|V-REGION|1..238|238 nt|1| | | | |238+0=238|partial in 5'| |
tcctagattttcaggtcgccagttccctaattatagctctgagctgaatgtgaacgcctt
ggagctggaggactcggccctgtatctctgtgccagcagc
>X61446|TRBV6-1*01|Homo sapiens|F|V-REGION|412..698|287 nt|1| | | | |287+0=287| | |
gctacaatgtctccagattaaacaaacgggagttctcgctcaggctggagtcggctgctc
cctcccagacatctgtgtacttctgtgccagcagtgaagc
>X61445|TRBV6-2*01|Homo sapiens|F|V-REGION|412..698|287 nt|1| | | | |287+0=287| | |
gctacaatgtctccagattaaaaaaacagaatttcctgctggggttggagtcggctgctc
cctcccaaacatctgtgtacttctgtgccagcagttactc
>U07978|TRBV6-3*01|Homo sapiens|F|V-REGION|29129..29415|287 nt|1| | | | |287+0=287| | |
gctacaatgtctccagattaaaaaaacagaatttcctgctggggttggagtcggctgctc
cctcccaaacatctgtgtacttctgtgccagcagttactc
>X61653|TRBV6-4*01|Homo sapiens|F|V-REGION|426..712|287 nt|1| | | | |287+0=287| | |
gttatagtgtctccagagcaaacacagatgatttccccctcacgttggcgtctgctgtac
cctctcagacatctgtgtacttctgtgccagcagtgactc
>AF009660|TRBV6-4*02|Homo sapiens|F|V-REGION|35797..36083|287 nt|1| | | | |287+0=287| | |
gttatagtgtctccagagcaaacacagatgatttccccctcacgttggcgtctgctgtac
cctctcagacatctgtgtacttctgtgccagcagtgactc
>L36092|TRBV6-5*01|Homo sapiens|F|V-REGION|265870..266156|287 nt|1| | | | |287+0=287| | |
gctacaatgtctccagatcaaccacagaggatttcccgctcaggctgctgtcggctgctc
cctcccagacatctgtgtacttctgtgccagcagttactc
>L36092|TRBV6-6*01|Homo sapiens|F|V-REGION|284442..284728|287 nt|1| | | | |287+0=287| | |
gctacaacgtctccagatcaaccacagaggatttcccgctcaggctggagttggctgctc
cctcccagacatctgtgtacttctgtgccagcagttactc
>AF009662|TRBV6-6*02|Homo sapiens|F|V-REGION|24864..25150|287 nt|1| | || |287+0=287| | |
gctacaacgtctccagatcaaccacagaggatttcccgctcaggctggagttggctgctc
cctcccagacatctgtgtacttctgtgccagcagttactc
>X58815|TRBV6-6*03|Homo sapiens|(F)|V-REGION|64..345|282 nt|1| | | | |282+0=282| | |
gaatggctacaacgtctccagatcaaccacagaggatttcccgctcaggctggagttggc
tgctccctcccagacatctgtgtacttctgtgccagcagt
>X74848|TRBV6-6*04|Homo sapiens|(F)|V-REGION|105..389|285 nt|1| | | | |285+0=285| | |
tggctacaatgtctccagatcaaccacagaggatttcccgctcaggctggagttggctgc
tccctcccagacatctgtgtacttctgtgccagcagtcga
>L06892|TRBV6-6*05|Homo sapiens|(F)|V-REGION|58..339|282 nt|1| | | | |282+0=282| | |
gaatggctacaacgtctccagatcaaccacagaggatttcccgctcaggctggagttggc
tgctgcctcccagacatctgtgtacttctgtgccagcagc
>L36092|TRBV6-7*01|Homo sapiens|ORF|V-REGION|302725..303011|287 nt|1| | | | |287+0=287| | |
gctacaatgtctccagatcaaacacagaggatttccccctcaagctggagtcagctgctc
cctctcagacttctgtttacttctgtgccagcagttactc
>L36092|TRBV6-8*01|Homo sapiens|F|V-REGION|322240..322523|284 nt|1| | | | |284+0=284| | |
gctacaatgtctctagattaaacacagaggatttcccactcaggctggtgtcggctgctc
cctcccagacatctgtgtacttgtgtgccagcagttactc
>X61447|TRBV6-9*01|Homo sapiens|F|V-REGION|380..666|287 nt|1| | | | |287+0=287| | |
gctacaatgtatccagatcaaacacagaggatttcccgctcaggctggagtcagctgctc
cctcccagacatctgtatacttctgtgccagcagttattc
>X61444|TRBV7-1*01|Homo sapiens|ORF|V-REGION|1332..1621|290 nt|1| | | | |290+0=290| | |
ggttctctgcacagaggtctgagggatccatctccactctgaagttccagcgcacacagc
agggggacttggctgtgtatctctgtgccagcagctcagc
>X61442|TRBV7-2*01|Homo sapiens|F|V-REGION|545..834|290 nt|1| | | | |290+0=290| | |
gcttctctgcagagaggactgggggatccgtctccactctgacgatccagcgcacacagc
aggaggactcggccgtgtatctctgtgccagcagcttagc
>L36190|TRBV7-2*02|Homo sapiens|F|V-REGION|9236..9525|290 nt|1| | || |290+0=290| | |
gcttctctgcagagaggactggggaatccgtctccactctgacgatccagcgcacacagc
aggaggactcggccgtgtatctctgtgccagcagcttagc
>U07975|TRBV7-2*03|Homo sapiens|F|V-REGION|7803..8092|290 nt|1| | | | |290+0=290| | |
gcttctctgcagagaggactggggaatccgtctccactctgacgatccagcgcacacagc
aggaggactcggccgtgtatctctgtaccagcagcttagc
>M27387|TRBV7-2*04|Homo sapiens|(F)|V-REGION|19..307|289 nt|1| | || |289+0=289| | |
cgcttctctgcagagaggactgggggatccgtctccactctgacgatccagcgcacacag
caggaggactcggccgtgtatctctgtgccagcagcttag
>X61440|TRBV7-3*01|Homo sapiens|F|V-REGION|748..1037|290 nt|1| | | | |290+0=290| | |
ggttctttgcagtcaggcctgagggatccgtctctactctgaagatccagcgcacagagc
ggggggactcagccgtgtatctctgtgccagcagcttaac
>M97943|TRBV7-3*02|Homo sapiens|ORF|V-REGION|404..693|290 nt|1| | | | |290+0=290| | |
ggttctttgcagtcaggcctgagggatccgtctctactctgaagatccagcgcacagagc
agggggactcagccgtgtatctccgtgccagcagcttaac
>AF009660|TRBV7-3*03|Homo sapiens|ORF|V-REGION|39374..39663|290 nt|1| | | | |290+0=290| | |
ggttctttgcagtcaggcctgagggatccgtctctactctgaagatccagcgcacagagc
agggggactcagccgcgtatctccgtgccagcagcttaac
>X74843|TRBV7-3*04|Homo sapiens|(F)|V-REGION|140..426|287 nt|1| | || |287+0=287| | |
atcggttctttgcagtcaggcctgagggatccgtctctactctgaagatccagcgcacag
agcggggggactctgccgtgtatctctgtgccagcagctt
>M13550|TRBV7-3*05|Homo sapiens|(F)|V-REGION|1..231|231 nt|1| | | | |231+0=231|partial in 5'| |
cgatcggttctttgcagtcaggcctgagggatccgtctctactctgaagatccagcgcac
agagcggggggactcagccgtgtatctctgtgccagcagc
>L36092|TRBV7-4*01|Homo sapiens|F|V-REGION|270051..270340|290 nt|1| | | | |290+0=290| | |
ggttctctgcagagaggcctgagagatccgtctccactctgaagatccagcgcacagagc
agggggactcagctgtgtatctctgtgccagcagcttagc
>L36092|TRBV7-6*01|Homo sapiens|F|V-REGION|307097..307386|290 nt|1| | | | |290+0=290| | |
ggttctctgcagagaggcctgagggatccatctccactctgacgatccagcgcacagagc
agcgggactcggccatgtatcgctgtgccagcagcttagc
>X58806|TRBV7-6*02|Homo sapiens|(F)|V-REGION|67..351|285 nt|1| | | | |285+0=285| | |
tgatcggttctctgcagagaggcctgagggatccatctccactctgacgatccagcgcac
agagcagcgggactcggccatgtatcgctgtgccagcagc
>L36092|TRBV7-7*01|Homo sapiens|F|V-REGION|326549..326838|290 nt|1| | | | |290+0=290| | |
ggttctctgcagagaggcctgagggatccatctccactctgacgattcagcgcacagagc
agcgggactcagccatgtatcgctgtgccagcagcttagc
>X57607|TRBV7-7*02|Homo sapiens|(F)|V-REGION|4..288|285 nt|1| | | | |285+0=285| | |
tgatcggttctctgcagagaggcctgagggatccatctccactctgacgattcagcgcac
agagcagcgggactcagccatgtatcgctgtgccagcagc
>M11953|TRBV7-8*01|Homo sapiens|F|V-REGION|215..504|290 nt|1| | | | |290+0=290| | |
gcttctttgcagaaaggcctgagggatccgtctccactctgaagatccagcgcacacagc
aggaggactccgccgtgtatctctgtgccagcagcttagc
>X61441|TRBV7-8*02|Homo sapiens|F|V-REGION|497..786|290 nt|1| | | | |290+0=290| | |
gcttctttgcagaaaggcctgagggatccgtctccactctgaagatccagcgcacacaga
aggaggactccgccgtgtatctctgtgccagcagcttagc
>M27384|TRBV7-8*03|Homo sapiens|(F)|V-REGION|25..312|288 nt|1| | | | |288+0=288| | |
tcgcttctttgcagaaaggcctgagggatccgtctccactctgaagatccagcgcacaca
gcaggaggactccgccgtgtatctctgtgccagcagccga
>L36092|TRBV7-9*01|Homo sapiens|F|V-REGION|364320..364609|290 nt|1| | | | |290+0=290| | |
ggttctctgcagagaggcctaagggatctttctccaccttggagatccagcgcacagagc
agggggactcggccatgtatctctgtgccagcagcttagc
>M15564|TRBV7-9*02|Homo sapiens|(F)|V-REGION|88..377|290 nt|1| | || |290+0=290| | |
ggttctctgcagagaggcctaagggatctttctccaccttggagatccagcgcacagagc
agggggactcggccatgtatctctgtgccagcagcttagc
>AF009663|TRBV7-9*03|Homo sapiens|F|V-REGION|108963..109252|290 nt|1| | || |290+0=290| | |
ggttctctgcagagaggcctaagggatctttctccaccttggagatccagcgcacagagc
agggggactcggccatgtatctctgtgccagcagcttagc
>M14261|TRBV7-9*04|Homo sapiens|(F)|V-REGION|58..342|285 nt|1| | || |285+0=285| | |
tgatcggatctctgcagagaggcctaagggatctttctccaccttggagatccagcgcac
agagcagggggactcggccatgtatctctgtgccagcagc
>M27385|TRBV7-9*05|Homo sapiens|(F)|V-REGION|34..321|288 nt|1| | | | |288+0=288| | |
tcggttctctgcagagaggcctaagggatctctctccaccttggagatccagcgcacaga
gcagggggactcggccatgtatctctgtgccagcaccaaa
>X74844|TRBV7-9*06|Homo sapiens|(F)|V-REGION|100..387|288 nt|1| | | | |288+0=288| | |
tcggttctctgcagagaggcctaagggatctctttccaccttggagatccagcgcacaga
gcagggggactcggccatgtatctctgtgccagcacgttg
>L14854|TRBV7-9*07|Homo sapiens|(F)|V-REGION|1..203|203 nt|1| | || |203+0=203|partial in 5'| |
atcggttctctgcagagaggcctaagggatctttctccaccttggagatccagcgcacag
aggagggggactcggccatgtatctctgtgccagcagcag
>L36092|TRBV9*01|Homo sapiens|F|V-REGION|206836..207121|286 nt|1| | | | |286+0=286| | |
cgattctccgcacaacagttccctgacttgcactctgaactaaacctgagctctctggag
ctgggggactcagctttgtatttctgtgccagcagcgtag
>AF009660|TRBV9*02|Homo sapiens|F|V-REGION|46949..47234|286 nt|1| | | | |286+0=286| | |
cgattctccgcacaacagttccctgacttgcactctgaactaaacctgagctctctggag
ctgggggactcagctttgtatttctgtgccagcagcgtag
>M27380|TRBV9*03|Homo sapiens|(F)|V-REGION|31..312|282 nt|1| | | | |282+0=282| | |
tgaacgattctccgcacaacagttccctgacttgcactctgaactaaacctgagctctct
ggagctgggggactcagctttgtatttctgtgccagcagc
