>L36092|TRBV10-1*01|Homo sapiens|F|V-REGION|214801..215087|287 nt|1| | | | |287+0=287| | |
ccattactcatatggtgttcaagacactaacaaaggagaagtctcagatggctacagtgt
ctctagatcaaacacagaggacctccccctcactctggagtctgctgcctcctcccagac
atctgtatatttctgcgccagcagtgagtc
>AF009660|TRBV10-1*02|Homo sapiens|F|V-REGION|54913..55199|287 nt|1| | || |287+0=287| | |
ccattactcatatggtgttcacgacactaacaaaggagaagtctcagatggctacagtgt
ctctagatcaaacacagaggacctccccctcactctggagtctgctgcctcctcccagac
atctgtatatttctgcgccagcagtgagtc
>L36092|TRBV10-2*01|Homo sapiens|F|V-REGION|239867..240153|287 nt|1| | | | |287+0=287| | |
ctattactcagcagctgctgatattacagataaaggagaagtccccgatggctatgttgt
ctccagatccaagacagagaatttccccctcactctggagtcagctacccgctcccagac
atctgtgtatttctgcgccagcagtgagtc
>U17048|TRBV10-2*02|Homo sapiens|[F]|V-REGION|1..217|217 nt|1| | | | |217+0=217|partial in 5'| |
ctgggacatgggctgaggctgatctattactcagcagctgctgatattacagataaagga
gaagtccccgatggctacgttgtctccagatccaagacagagaatttccccctcactctg
gagtcagctacccgctcccagacatctgtg
>U03115|TRBV10-3*01|Homo sapiens|F|V-REGION|14880..15166|287 nt|1| | | | |287+0=287| | |
ccattactcatatggtgttaaagatactgacaaaggagaagtctcagatggctatagtgt
ctctagatcaaagacagaggatttcctcctcactctggagtccgctaccagctcccagac
atctgtgtacttctgtgccatcagtgagtc
>U17047|TRBV10-3*02|Homo sapiens|F|V-REGION|81..367|287 nt|1| | | | |287+0=287| | |
ccattactcatatggtgttaaagatactgacaaaggagaagtctcagatggctatagtgt
ctctagatcaaagacagaggatttcctcctcactctggagtccgctaccagctcccagac
atctgtgtacttctgtgccatcagtgagtc
>L33101|TRBV10-3*03|Homo sapiens|[F]|V-REGION|1..273|273 nt|1| | | | |273+0=273| | |
gggctgaggctaatccattactcatatggtgttaaagatactgacaaaggagaagtctca
gatggctatagtgtctctagatcaaagacagaggatttcctcctcactctggagtccgct
accagctcccagacatctgtgtacttctgt
>L33102|TRBV10-3*04|Homo sapiens|[F]|V-REGION|1..273|273 nt|1| | | | |273+0=273| | |
gggctgaggctgatccattactcatatggtgttaaagatactgacaaaggagaagtctca
gatggctatagtgtctctagatcaaagacagaggatttcctcctcactctggagtccgct
accagctcccagacatctgtgtacttctgt
>M33233|TRBV11-1*01|Homo sapiens|F|V-REGION|747..1036|290 nt|1| | | | |290+0=290| | |
tcaatttcaggatgagagtgtagtagatgattcacagttgcctaaggatcgattttctgc
agagaggctcaaaggagtagactccactctcaagatccagcctgcagagcttggggactc
ggccatgtatctctgtgccagcagcttagc
>L36092|TRBV11-2*01|Homo sapiens|F|V-REGION|248813..249102|290 nt|1| | | | |290+0=290| | |
tcagtttcagaataacggtgtagtggatgattcacagttgcctaaggatcgattttctgc
agagaggctcaaaggagtagactccactctcaagatccagcctgcaaagcttgaggactc
ggccgtgtatctctgtgccagcagcttaga
>M33235|TRBV11-2*02|Homo sapiens|[F]|V-REGION|171..455|285 nt|1| | | | |285+0=285| | |
ctgattcagtttcagaataacggtgtagtggatgattcacagttgcctaaggatcgattt
tctgcagagaggctcaaaggagtagactccactctcaagatccagcctgcaaagcttgag
aactcggccgtgtatctctgtgccagcagt
>X58796|TRBV11-2*03|Homo sapiens|(F)|V-REGION|81..365|285 nt|1| | | | |285+0=285| | |
ctgattcagtttcagaataacggtgtagtggatgattcacagttgcctaaggatcgattt
tctgcagagaggctcaaaggagtagactccactctcaagatccaacctgcaaagcttgag
gactcggccgtgtatctctgtgccagcagc
>U03115|TRBV11-3*01|Homo sapiens|F|V-REGION|25513..25802|290 nt|1| | | | |290+0=290| | |
tcgatatgagaatgaggaagcagtagacgattcacagttgcctaaggatcgattttctgc
agagaggctcaaaggagtagactccactctcaagatccagcctgcagagcttggggactc
ggccgtgtatctctgtgccagcagcttaga
>X58797|TRBV11-3*02|Homo sapiens|(F)|V-REGION|103..387|285 nt|1| | | | |285+0=285| | |
ctgattcgatatgagaatgaggaagcagtagacgattcacagttgcctaaggatcgattt
tctgcagagaggctcaaaggagtagactccactctcaagatccagcctgcagagcttggg
gactcggccgtgtatctctgtgccagcagc
>M62377|TRBV11-3*03|Homo sapiens|(F)|V-REGION|1..269|269 nt|1| | | | |269+0=269|partial in 5'| |
ctgattcgatatgagaatgaggaagcagtagacgattcacagttgcctaaggatcgattt
tctgcagagaggctcaaaggagtagactccactctcaagatccagccagcagagcttggg
gactcggccatgtatctctgtgccagcagc
>X07192|TRBV12-3*01|Homo sapiens|F|V-REGION|426..715|290 nt|1| | | | |290+0=290| | |
ttactttaacaacaacgttccgatagatgattcagggatgcccgaggatcgattctcagc
taagatgcctaatgcatcattctccactctgaagatccagccctcagaacccagggactc
agctgtgtacttctgtgccagcagtttagc
>K02546|TRBV12-4*01|Homo sapiens|F|V-REGION|158..447|290 nt|1| | | | |290+0=290| | |
ttactttaacaacaacgttccgatagatgattcagggatgcccgaggatcgattctcagc
taagatgcctaatgcatcattctccactctgaagatccagccctcagaacccagggactc
agctgtgtacttctgtgccagcagtttagc
>M14264|TRBV12-4*02|Homo sapiens|(F)|V-REGION|58..345|288 nt|1| | | | |288+0=288| | |
atttactttaacaacaacgttccgatagatgattcagggatgcccgaggatcgattctca
gctaagatgcctaatgcatcattctccactctgaggatccagccctcagaacccagggac
tcagctgtgtacttctgtgccagcagttta
>X07223|TRBV12-5*01|Homo sapiens|F|V-REGION|392..681|290 nt|1| | | | |290+0=290| | |
ttacttccgcaaccgggctcctctagatgattcggggatgccgaaggatcgattctcagc
agagatgcctgatgcaactttagccactctgaagatccagccctcagaacccagggactc
agctgtgtatttttgtgctagtggtttggt
>U03115|TRBV13*01|Homo sapiens|F|V-REGION|6502..6788|287 nt|1| | | | |287+0=287| | |
catttcgttttatgaaaagatgcagagcgataaaggaagcatccctgatcgattctcagc
tcaacagttcagtgactatcattctgaactgaacatgagctccttggagctgggggactc
agccctgtacttctgtgccagcagcttagg
>M62378|TRBV13*02|Homo sapiens|(F)|V-REGION|128..409|282 nt|1| | | | |282+0=282| | |
ttcttcatttcgttttatgaaaagatgcagagcgataaaggaagcatccctgatcgattc
tcagctcaacagttcagtgactatcattctgaactgaacatgagctccttggagctgggg
gactcagccctgtacttctgtgccagcagc
>X06154|TRBV14*01|Homo sapiens|F|V-REGION|283..572|290 nt|1| | | | |290+0=290| | |
acattttgtgaaagagtctaaacaggatgagtccggtatgcccaacaatcgattcttagc
tgaaaggactggagggacgtattctactctgaaggtgcagcctgcagaactggaggattc
tggagtttatttctgtgccagcagccaaga
>X57722|TRBV14*02|Homo sapiens|(F)|V-REGION|46..330|285 nt|1| | | | |285+0=285| | |
ctgttacattttgtgaaagagtctaaacaggatgaatccggtatgcccaacaatcgattc
ttagctgaaaggactggagggacgtattctactctgaaggtgcagcctgcagaactggag
gattctggagtttatttctgtgccagcagc
>U03115|TRBV15*01|Homo sapiens|F|V-REGION|63681..63967|287 nt|1| | | | |287+0=287| | |
gttccactactatgacaaagattttaacaatgaagcagacacccctgataacttccaatc
caggaggccgaacacttctttctgctttcttgacatccgctcaccaggcctgggggacac
agccatgtacctgtgtgccaccagcagaga
>X58800|TRBV15*02|Homo sapiens|(F)|V-REGION|85..366|282 nt|1| | | | |282+0=282| | |
ctgctgttccactactatgacaaagattttaacaatgaagcagacacccctgataacttc
caatccaggaggccgaacacttctttctgctttcttgacatccgctcaccaggcctgggg
gacgcagccatgtacctgtgtgccaccagc
>M62376|TRBV15*03|Homo sapiens|(F)|V-REGION|135..416|282 nt|1| | | | |282+0=282| | |
ctgctgttccactactataacaaagattttaacaatgaagcagacacccctgataacttc
caatccaggaggccgaacacttctttctgctttctagacatccgctcaccaggcctgggg
gacgcagccatgtaccagtgtgccaccagc
>L26231|TRBV16*01|Homo sapiens|F|V-REGION|419..708|290 nt|1| | | | |290+0=290| | |
ttccttccagaatgaaaatgtctttgatgaaacaggtatgcccaaggaaagattttcagc
taagtgcctcccaaattcaccctgtagccttgagatccaggctacgaagcttgaggattc
agcagtgtatttttgtgccagcagccaatc
>L26054|TRBV16*03|Homo sapiens|(F)|V-REGION|58..342|285 nt|1| | | | |285+0=285| | |
ttggtttccttccagaatgaaaatgtctttgatgaaacaggtatgcccaaggaaagattt
tcagctaagtgcctcccaaattcaccctgtagccttgagatccaggctacgaagcttgag
gattcagcagtgtatttttgtgccagcagc
>U03115|TRBV17*01|Homo sapiens|ORF|V-REGION|72572..72858|287 nt|1| | | | |287+0=287| | |
gatttccttccagtaccaaaacattgcagttgattcagggatgcccaaggaacgattcac
agctgaaagacctaacggaacgtcttccacgctgaagatccatcccgcagagccgaggga
ctcagccgtgtatctctacagtagcggtgg
>L36092|TRBV18*01|Homo sapiens|F|V-REGION|450875..451164|290 nt|1| | | | |290+0=290| | |
ttatctccagaaagaaaatatcatagatgagtcaggaatgccaaaggaacgattttctgc
tgaatttcccaaagagggccccagcatcctgaggatccagcaggtagtgcgaggagattc
ggcagcttatttctgtgccagctcaccacc
>L36092|TRBV19*01|Homo sapiens|F|V-REGION|453995..454281|287 nt|1| | | | |287+0=287| | |
ctactactcacagatagtaaatgactttcagaaaggagatatagctgaagggtacagcgt
ctctcgggagaagaaggaatcctttcctctcactgtgacatcggcccaaaagaacccgac
agctttctatctctgtgccagtagtataga
>U48259|TRBV19*02|Homo sapiens|F|V-REGION|239..525|287 nt|1| | | | |287+0=287| | |
ctactactcacacatagtaaatgactttcagaaaggagatatagctgaagggtacagcgt
ctctcgggagaagaaggaatcctttcctctcactgtgacatcggcccaaaagaacccgac
agctttctatctctgtgccagtagtataga
>M97725|TRBV19*03|Homo sapiens|(F)|V-REGION|58..338|281 nt|1| | || |281+0=281| | |
attgatctactactcacacatagtaaatgactttcagaaaggagatatagctgaagggta
cagcgtctctcgggagaagaaggaatcctttcctctcactgtgacatcggcccaaaagaa
cccgacagctttctatctctgtgccagtag
>L36092|TRBV2*01|Homo sapiens|F|V-REGION|93697..93986|290 nt|1| | | | |290+0=290| | |
ttccttttataataatgaaatctcagagaagtctgaaatattcgatgatcaattctcagt
tgaaaggcctgatggatcaaatttcactctgaagatccggtccacaaagctggaggactc
agccatgtacttctgtgccagcagtgaagc
>M62379|TRBV2*02|Homo sapiens|(F)|V-REGION|1..285|285 nt|1| | | | |285+0=285| | |
ctggtttccttttataataatgaaatctcagagaagtctgaaatattcgatgatcaattc
tcagttgaaaggcctgatggatcaaatttcactctgaagatccggtccacaaagctggag
gactcagccatgtacttctgtgccagcagt
>M64351|TRBV2*03|Homo sapiens|(F)|V-REGION|82..369|288 nt|1| | | | |288+0=288| | |
gtttccttttataataatgaaatctcagagaagtctgaaatattcgatgatcaattctca
gttgagaggcctgatggatcaaatttcactctgaagatccggtccacaaagctggaggac
tcagccatgtacttctgtgccagcagtgaa
>M11955|TRBV20-1*01|Homo sapiens|F|V-REGION|427..719|293 nt|1| | | | |293+0=293| | |
aacttccaatgagggctccaaggccacatacgagcaaggcgtcgagaaggacaagtttct
catcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgcccatcctgaaga
cagcagcttctacatctgcagtgctagaga
>X72719|TRBV20-1*02|Homo sapiens|F|V-REGION|381..668|288 nt|1| | | | |288+0=288| | |
atggcaacttccaatgagggctccaaggccacatacgagcaaggcgtcgagaaggacaag
tttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgcccatcct
gaagacagcagcttctacatctgcagtgct
>M11954|TRBV20-1*03|Homo sapiens|(F)|V-REGION|427..714|288 nt|1| | | | |288+0=288| | |
atggcaacttccaatgagggctgcaaggccacatacgagcaaggcgtcgagaaggacaag
tttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgcccatcct
gaagacagcagcttctacatctgcagtgct
>M14263|TRBV20-1*04|Homo sapiens|(F)|V-REGION|46..336|291 nt|1| | | | |291+0=291| | |
gcaacttccaatgagggctccaaggccacatacgagcaaggcgtcgagaaggacaagttt
ctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgcccatcctgaa
gacagcagcttctacatctgcagtgctagt
>X57604|TRBV20-1*05|Homo sapiens|(F)|V-REGION|396..686|291 nt|1| | | | |291+0=291| | |
gcaacttccaatgagggctccaaggccacatacgagcaaggcgtcgagaaggacaagttt
ctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgcccatcctgaa
gacagcagcttctacatctgcagtgctaga
>D13088|TRBV20-1*06|Homo sapiens|(F)|V-REGION|43..330|288 nt|1| | | | |288+0=288| | |
atggcaacttccaatgagggctccaaggccacatacgagcaaggcgtcgagaaggacaag
tttctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgcccatcct
gaagacagcagcttctacatctgcagtgct
>X74852|TRBV20-1*07|Homo sapiens|(F)|V-REGION|64..354|291 nt|1| | | | |291+0=291| | |
gcaacttccaatgagggctccaaggccacatacgagcaaggcgtcgagaaggacaagttt
ctcatcaaccatgcaagcctgaccttgtccactctgacagtgaccagtgcccatcctgaa
gacagcagcttctacatctgcagtgctaga
>L36092|TRBV23-1*01|Homo sapiens|ORF|V-REGION|480906..481195|290 nt|1| | | | |290+0=290| | |
ttcctttcagaatgaacaagttcttcaagaaacggagatgcacaagaagcgattctcatc
tcaatgccccaagaacgcaccctgcagcctggcaatcctgtcctcagaaccgggagacac
ggcactgtatctctgcgccagcagtcaatc
>M11951|TRBV24-1*01|Homo sapiens|F|V-REGION|189..476|288 nt|1| | | | |288+0=288| | |
tattactcctttgatgtcaaagatataaacaaaggagagatctctgatggatacagtgtc
tctcgacaggcacaggctaaattctccctgtccctagagtctgccatccccaaccagaca
gctctttacttctgtgccaccagtgatttg
>L36092|TRBV25-1*01|Homo sapiens|F|V-REGION|504596..504882|287 nt|1| | | | |287+0=287| | |
ccactattcctatggagttaattccacagagaagggagatctttcctctgagtcaacagt
ctccagaataaggacggagcattttcccctgaccctggagtctgccaggccctcacatac
ctctcagtacctctgtgccagcagtgaata
>L36092|TRBV26*01|Homo sapiens|P|V-REGION|529534..529820|287 nt|1| | | | |287+0=287| | |
ctattattcacctggcactgggagcactgaaaaaggagatatctctgaggggtatcatgt
ttcttgaaatactatagcatcttttcccctgaccctgaagtctgccagcaccaaccagac
atctgtgtatctctatgccagcagttcatc
>L36092|TRBV27*01|Homo sapiens|F|V-REGION|549224..549510|287 nt|1| | | | |287+0=287| | |
ctactattcaatgaatgttgaggtgactgataagggagatgttcctgaagggtacaaagt
ctctcgaaaagagaagaggaatttccccctgatcctggagtcgcccagccccaaccagac
ctctctgtacttctgtgccagcagtttatc
>U08314|TRBV28*01|Homo sapiens|F|V-REGION|408..694|287 nt|1| | | | |287+0=287| | |
ctatttctcatatgatgttaaaatgaaagaaaaaggagatattcctgaggggtacagtgt
ctctagagagaagaaggagcgcttctccctgattctggagtccgccagcaccaaccagac
atctatgtacctctgtgccagcagtttatg
>L36092|TRBV29-1*01|Homo sapiens|F|V-REGION|574270..574559|290 nt|1| | | | |290+0=290| | |
aactgcaaatcagggctctgaggccacatatgagagtggatttgtcattgacaagtttcc
catcagccgcccaaacctaacattctcaactctgactgtgagcaacatgagccctgaaga
cagcagcatatatctctgcagcgttgaaga
>M13847|TRBV29-1*02|Homo sapiens|(F)|V-REGION|17..304|288 nt|1| | | | |288+0=288| | |
gcaactgcaaatcagggctctgaggccacatatgagagtggatttgtcattgacaagttt
cccatcagccgcccaaacctaacattctcaagtctgactgtgagcaacatgagccctgaa
gacagcagcatatatctctgcagcgttgaa
>X04926|TRBV29-1*03|Homo sapiens|(F)|V-REGION|1..231|231 nt|1| | | | |231+0=231|partial in 5'| |
gcaactgcaaatcagggctctgaggccacatatgagagtggatttgtcattgacaagttt
cccatcagccgcccaaacctaacattctcaactctgactgtgagcaacatgagccctgaa
gacagcagcatatatctctgcagcgcgggc
>U07977|TRBV3-1*01|Homo sapiens|F|V-REGION|5648..5934|287 nt|1| | | | |287+0=287| | |
gtttagctacaataataaggagctcattataaatgaaacagttccaaatcgcttctcacc
taaatctccagacaaagctcacttaaatcttcacatcaattccctggagcttggtgactc
tgctgtgtatttctgtgccagcagccaaga
>L06889|TRBV3-1*02|Homo sapiens|(F)|V-REGION|58..336|279 nt|1| | | | |279+0=279| | |
aagataatgtttagctacaataacaaggagatcattataaatgaaacagttccaaatcga
ttctcacctaaatctccagacaaagctaaattaaatcttcacatcaattccctggagctt
ggtgactctgctgtgtatttctgtgccagc
>L36092|TRBV30*01|Homo sapiens|F|V-REGION|666640..666923|284 nt|1| | | | |284+0=284| | |
gctgctcttctactccgttggtattggccagatcagctctgaggtgccccagaatctctc
agcctccagaccccaggaccggcagttcatcctgagttctaagaagctccttctcagtga
ctctggcttctatctctgtgcctggagtgt
>Z13967|TRBV30*02|Homo sapiens|F|V-REGION|416..699|284 nt|1| | | | |284+0=284| | |
gctgctcttctactccgttggtattggccagatcagctctgaggtgccccagaatctctc
agcctccagaccccaggaccggcagttcatcctgagttctaagaagctcctcctcagtga
ctctggcttctatctctgtgcctggagtgt
>M13554|TRBV30*04|Homo sapiens|(F)|V-REGION|1..276|276 nt|1| | | | |276+0=276| | |
cagctgctcttctactccattggtattgaccagatcagctctgaggtgccccagaatctc
tcagcctccagaccccaggaccggcagttcattctgagttctaagaagctcctcctcagt
gactctggcttctatctctgtgcctggagt
>L06893|TRBV30*05|Homo sapiens|(F)|V-REGION|52..333|282 nt|1| | | | |282+0=282| | |
cagctgctcttctactccgttggtattggccagatcagctctgaggtgccccagaatctc
tcagcctccagaccccaggaccggcagttcatcctgagttctaagaagctccttctcagt
gactctggcttctatctctgtgcctgggga
>U07977|TRBV4-1*01|Homo sapiens|F|V-REGION|10268..10554|287 nt|1| | | | |287+0=287| | |
gtttgtctacagctatgagaaactctctataaatgaaagtgtgccaagtcgcttctcacc
tgaatgccccaacagctctctcttaaaccttcacctacacgccctgcagccagaagactc
agccctgtatctctgcgccagcagccaaga
>M13855|TRBV4-1*02|Homo sapiens|(F)|V-REGION|1..259|259 nt|1| | || |259+0=259|partial in 5'| |
tgtttgtctacagctatgagaaactctctataaatgaaagtgtgccaagtcgcttctcac
ctgaatgccccaacagctctctcttaaaccttcacctacacgccctgcagccagaagact
cagccctgtatctctgcgccagcagccaag
>U07975|TRBV4-2*01|Homo sapiens|F|V-REGION|477..763|287 nt|1| | | | |287+0=287| | |
gtttgtctacaactttaaagaacagactgaaaacaacagtgtgccaagtcgcttctcacc
tgaatgccccaacagctctcacttattccttcacctacacaccctgcagccagaagactc
ggccctgtatctctgtgccagcagccaaga
>X58811|TRBV4-2*02|Homo sapiens|(F)|V-REGION|169..450|282 nt|1| | | | |282+0=282| | |
ctcatgtttgtctacaactttaaagaacagactgaaaacaacagtgtgccaagtcgcttc
tcacctgaatgccccaacagctctcacttatgccttcacctacacaccctgcagccagaa
gactcggccctgtatctctgtgccagcacc
>U07978|TRBV4-3*01|Homo sapiens|F|V-REGION|20940..21226|287 nt|1| | | | |287+0=287| | |
gtttgtctacagtcttgaagaacgggttgaaaacaacagtgtgccaagtcgcttctcacc
tgaatgccccaacagctctcacttattccttcacctacacaccctgcagccagaagactc
ggccctgtatctctgcgccagcagccaaga
>X58812|TRBV4-3*02|Homo sapiens|(F)|V-REGION|73..354|282 nt|1| | | | |282+0=282| | |
ctcatgtttgtctacagtcttgaagaacgggttgaaaacaacagtgtgccaagtcgcttc
tcacctgaatgccccaacagctctcacttatcccttcacctacacaccctgcagccagaa
gactcggccctgtatctctgcgccagcagc
>L06888|TRBV4-3*03|Homo sapiens|(F)|V-REGION|58..339|282 nt|1| | | | |282+0=282| | |
ctcatgtttgtctacagtcttgaagaacgtgttgaaaacaacagtgtgccaagtcgcttc
tcacctgaatgccccaacagctctcacttattccttcacctacacaccctgcagccagaa
gactcggccctgtatctctgcgccagcagc
>X57616|TRBV4-3*04|Homo sapiens|(F)|V-REGION|1..231|231 nt|1| | | | |231+0=231|partial in 5'| |
ctcatgtttgtctacagtcttgaagaacgggttgaaaacaacagtgtgccaagtcgcttc
tcacctgaatgccccaacagctctcacttattccttcacctacacaccctgcagccagaa
gactcggccctgtatctctgcgccagcagc
>L36092|TRBV5-1*01|Homo sapiens|F|V-REGION|113806..114091|286 nt|1| | | | |286+0=286| | |
tctttgaatacttcagtgagacacagagaaacaaaggaaacttccctggtcgattctcag
ggcgccagttctctaactctcgctctgagatgaatgtgagcaccttggagctgggggact
cggccctttatctttgcgccagcagcttgg
>M14271|TRBV5-1*02|Homo sapiens|(F)|V-REGION|50..328|279 nt|1| | || |279+0=279| | |
cagttcctctttgaatacttcagtgagacacagagaaacaaaggaaacttccttggtcga
ttctcagggcgccagttctctaactctcgctctgagatgaatgtgagcaccttggagctg
ggggactcggccctttatctttgcgccagc
>X61439|TRBV5-3*01|Homo sapiens|ORF|V-REGION|417..702|286 nt|1| | | | |286+0=286| | |
tctttgaatatgctaatgagttaaggagatcagaaggaaacttccctaatcgattctcag
ggcgccagttccatgactgttgctctgagatgaatgtgagtgccttggagctgggggact
cggccctgtatctctgtgccagaagcttgg
>AF009660|TRBV5-3*02|Homo sapiens|ORF|V-REGION|44205..44490|286 nt|1| | | | |286+0=286| | |
tctttgaatatgctaatgagttaaggagatcagaaggaaacttccctaatcgattctcag
ggcgccagttccatgactattgctctgagatgaatgtgagtgccttggagctgggggact
cggccctgtatctctgtgccagaagcttgg
>L36092|TRBV5-4*01|Homo sapiens|F|V-REGION|278005..278290|286 nt|1| | | | |286+0=286| | |
tctttcagtattatagggaggaagagaatggcagaggaaacttccctcctagattctcag
gtctccagttccctaattatagctctgagctgaatgtgaacgccttggagctggacgact
cggccctgtatctctgtgccagcagcttgg
>X57615|TRBV5-4*02|Homo sapiens|(F)|V-REGION|65..346|282 nt|1| | | | |282+0=282| | |
tttatctttcagtattatagggaggaagagaatggcagaggaaacttccctcctagattc
tcaggtctccagttccctaattataactctgagctgaatgtgaacgccttggagctggac
gactcggccctgtatctctgtgccagcagc
>S50547|TRBV5-4*03|Homo sapiens|(F)|V-REGION|1..234|234 nt|1| | | | |234+0=234|partial in 5'| |
tttatctttcagtattatagggaggaagagaatggcagaggaaacttccctcctagattc
tcaggtctccagttccctaattatagctctgagctgaatgtgaacgccttggagctggac
gactcggccctgtatctctgtgccagcagc
>X58804|TRBV5-4*04|Homo sapiens|(F)|V-REGION|1..192|192 nt|1| | | | |192+0=192|partial in 5'| |
tttatctttcagtattatagggaggaagagaatggcagaggaaactcccctcctagattc
tcaggtctccagttccctaattatagctctgagctgaatgtgaacgccttggagctggac
gactcggccctgtatctctgtgccagcagc
>L36092|TRBV5-5*01|Homo sapiens|F|V-REGION|297450..297735|286 nt|1| | | | |286+0=286| | |
tctttcagtattatgagaaagaagagagaggaagaggaaacttccctgatcgattctcag
ctcgccagttccctaactatagctctgagctgaatgtgaacgccttgttgctgggggact
cggccctgtatctctgtgccagcagcttgg
>X57611|TRBV5-5*02|Homo sapiens|(F)|V-REGION|65..346|282 nt|1| | | | |282+0=282| | |
tttatctttcagtattatgagaaagaagagagaggaagaggaaacttccctgatcgattc
tcagctcgccagttccctaactatagctctgagctgaatgtgaacgccttgttgctgggg
gactcggccctgtatctctgtgccagcagc
>X58801|TRBV5-5*03|Homo sapiens|(F)|V-REGION|129..410|282 nt|1| | | | |282+0=282| | |
tttatctttcagtattatgagaaagaagagagaggaagaggaaacttccctgatcgattc
tcagctcgccagttccctaactatagctctgagctgaatgtgaacgccttgttgctgggg
gactcggccctgtatctctgtgccagcagc
>L36092|TRBV5-6*01|Homo sapiens|F|V-REGION|314963..315248|286 nt|1| | | | |286+0=286| | |
tctttcagtattatgaggaggaagagagacagagaggcaacttccctgatcgattctcag
gtcaccagttccctaactatagctctgagctgaatgtgaacgccttgttgctgggggact
cggccctctatctctgtgccagcagcttgg
>L36092|TRBV5-7*01|Homo sapiens|ORF|V-REGION|334981..335266|286 nt|1| | | | |286+0=286| | |
tctttcagtattatgagaaagaagagagaggaagaggaaacttccctgatcaattctcag
gtcaccagttccctaactatagctctgagctgaatgtgaacgccttgttgctaggggact
cggccctctatctctgtgccagcagcttgg
>L36092|TRBV5-8*01|Homo sapiens|F|V-REGION|355117..355402|286 nt|1| | | | |286+0=286| | |
tcctttggtatgacgagggtgaagagagaaacagaggaaacttccctcctagattttcag
gtcgccagttccctaattatagctctgagctgaatgtgaacgccttggagctggaggact
cggccctgtatctctgtgccagcagcttgg
>X58803|TRBV5-8*02|Homo sapiens|(F)|V-REGION|1..238|238 nt|1| | | | |238+0=238|partial in 5'| |
ctcctcctttggtatgacgagggtgaagagagaaacagaggaaacttccctcctagattt
tcaggtcgccagttccctaattatagctctgagctgaatgtgaacgccttggagctggag
gactcggccctgtatctctgtgccagcagc
>X61446|TRBV6-1*01|Homo sapiens|F|V-REGION|412..698|287 nt|1| | | | |287+0=287| | |
ttattactcagcttctgagggtaccactgacaaaggagaagtccccaatggctacaatgt
ctccagattaaacaaacgggagttctcgctcaggctggagtcggctgctccctcccagac
atctgtgtacttctgtgccagcagtgaagc
>X61445|TRBV6-2*01|Homo sapiens|F|V-REGION|412..698|287 nt|1| | | | |287+0=287| | |
tcattactcagttggtgagggtacaactgccaaaggagaggtccctgatggctacaatgt
ctccagattaaaaaaacagaatttcctgctggggttggagtcggctgctccctcccaaac
atctgtgtacttctgtgccagcagttactc
>U07978|TRBV6-3*01|Homo sapiens|F|V-REGION|29129..29415|287 nt|1| | | | |287+0=287| | |
tcattactcagttggtgagggtacaactgccaaaggagaggtccctgatggctacaatgt
ctccagattaaaaaaacagaatttcctgctggggttggagtcggctgctccctcccaaac
atctgtgtacttctgtgccagcagttactc
>X61653|TRBV6-4*01|Homo sapiens|F|V-REGION|426..712|287 nt|1| | | | |287+0=287| | |
ccattattcaaatactgcaggtaccactggcaaaggagaagtccctgatggttatagtgt
ctccagagcaaacacagatgatttccccctcacgttggcgtctgctgtaccctctcagac
atctgtgtacttctgtgccagcagtgactc
>AF009660|TRBV6-4*02|Homo sapiens|F|V-REGION|35797..36083|287 nt|1| | | | |287+0=287| | |
ccattattcaaatactgcaggtaccactggcaaaggagaagtccctgatggttatagtgt
ctccagagcaaacacagatgatttccccctcacgttggcgtctgctgtaccctctcagac
atctgtgtacttctgtgccagcagtgactc
>L36092|TRBV6-5*01|Homo sapiens|F|V-REGION|265870..266156|287 nt|1| | | | |287+0=287| | |
tcattactcagttggtgctggtatcactgaccaaggagaagtccccaatggctacaatgt
ctccagatcaaccacagaggatttcccgctcaggctgctgtcggctgctccctcccagac
atctgtgtacttctgtgccagcagttactc
>L36092|TRBV6-6*01|Homo sapiens|F|V-REGION|284442..284728|287 nt|1| | | | |287+0=287| | |
ttattattcagttggtgctggtatcactgataaaggagaagtcccgaatggctacaacgt
ctccagatcaaccacagaggatttcccgctcaggctggagttggctgctccctcccagac
atctgtgtacttctgtgccagcagttactc
>AF009662|TRBV6-6*02|Homo sapiens|F|V-REGION|24864..25150|287 nt|1| | || |287+0=287| | |
ttattattcagttggtgctggtatcactgacaaaggagaagtcccgaatggctacaacgt
ctccagatcaaccacagaggatttcccgctcaggctggagttggctgctccctcccagac
atctgtgtacttctgtgccagcagttactc
>X58815|TRBV6-6*03|Homo sapiens|(F)|V-REGION|64..345|282 nt|1| | | | |282+0=282| | |
ctgatttattattcagttggtgctggtatcactgataaaggagaagtcccgaatggctac
aacgtctccagatcaaccacagaggatttcccgctcaggctggagttggctgctccctcc
cagacatctgtgtacttctgtgccagcagt
>X74848|TRBV6-6*04|Homo sapiens|(F)|V-REGION|105..389|285 nt|1| | | | |285+0=285| | |
atttattattcagttggtgctggtatcactgataaaggagaagtcccgaatggctacaat
gtctccagatcaaccacagaggatttcccgctcaggctggagttggctgctccctcccag
acatctgtgtacttctgtgccagcagtcga
>L06892|TRBV6-6*05|Homo sapiens|(F)|V-REGION|58..339|282 nt|1| | | | |282+0=282| | |
ctgatttattattcagttggtgctggtatcactgacaaaggagaagtcccgaatggctac
aacgtctccagatcaaccacagaggatttcccgctcaggctggagttggctgctgcctcc
cagacatctgtgtacttctgtgccagcagc
>L36092|TRBV6-7*01|Homo sapiens|ORF|V-REGION|302725..303011|287 nt|1| | | | |287+0=287| | |
ttactactcagttgctgctgctctcactgacaaaggagaagttcccaatggctacaatgt
ctccagatcaaacacagaggatttccccctcaagctggagtcagctgctccctctcagac
ttctgtttacttctgtgccagcagttactc
>L36092|TRBV6-8*01|Homo sapiens|F|V-REGION|322240..322523|284 nt|1| | | | |284+0=284| | |
gatttactactcagctgctgctggtactactgacaaagaagtccccaatggctacaatgt
ctctagattaaacacagaggatttcccactcaggctggtgtcggctgctccctcccagac
atctgtgtacttgtgtgccagcagttactc
>X61447|TRBV6-9*01|Homo sapiens|F|V-REGION|380..666|287 nt|1| | | | |287+0=287| | |
tcattactcagttgctgctggtatcactgacaaaggagaagtccccgatggctacaatgt
atccagatcaaacacagaggatttcccgctcaggctggagtcagctgctccctcccagac
atctgtatacttctgtgccagcagttattc
>X61444|TRBV7-1*01|Homo sapiens|ORF|V-REGION|1332..1621|290 nt|1| | | | |290+0=290| | |
ttacttccaaggcaaggatgcagcagacaaatcggggcttccccgtgatcggttctctgc
acagaggtctgagggatccatctccactctgaagttccagcgcacacagcagggggactt
ggctgtgtatctctgtgccagcagctcagc
>X61442|TRBV7-2*01|Homo sapiens|F|V-REGION|545..834|290 nt|1| | | | |290+0=290| | |
ttacttccaaggcaacagtgcaccagacaaatcagggctgcccagtgatcgcttctctgc
agagaggactgggggatccgtctccactctgacgatccagcgcacacagcaggaggactc
ggccgtgtatctctgtgccagcagcttagc
>L36190|TRBV7-2*02|Homo sapiens|F|V-REGION|9236..9525|290 nt|1| | || |290+0=290| | |
ttacttccaaggcaacagtgcaccagacaaatcagggctgcccagtgatcgcttctctgc
agagaggactggggaatccgtctccactctgacgatccagcgcacacagcaggaggactc
ggccgtgtatctctgtgccagcagcttagc
>U07975|TRBV7-2*03|Homo sapiens|F|V-REGION|7803..8092|290 nt|1| | | | |290+0=290| | |
ttacttccaaggcaacagtgcaccagacaaatcagggctgcccagtgatcgcttctctgc
agagaggactggggaatccgtctccactctgacgatccagcgcacacagcaggaggactc
ggccgtgtatctctgtaccagcagcttagc
>M27387|TRBV7-2*04|Homo sapiens|(F)|V-REGION|19..307|289 nt|1| | || |289+0=289| | |
tttacttccaaggcaacagtgcaccagacaaatcagggctgcccagtgatcgcttctctg
cagagaggactgggggatccgtctccactctgacgatccagcgcacacagcaggaggact
cggccgtgtatctctgtgccagcagcttag
>X61440|TRBV7-3*01|Homo sapiens|F|V-REGION|748..1037|290 nt|1| | | | |290+0=290| | |
ttacttccaaggcacgggtgcggcagatgactcagggctgcccaacgatcggttctttgc
agtcaggcctgagggatccgtctctactctgaagatccagcgcacagagcggggggactc
agccgtgtatctctgtgccagcagcttaac
>M97943|TRBV7-3*02|Homo sapiens|ORF|V-REGION|404..693|290 nt|1| | | | |290+0=290| | |
ttacttccaaggcacgggtgcggcagatgactcagggctgcccaaagatcggttctttgc
agtcaggcctgagggatccgtctctactctgaagatccagcgcacagagcagggggactc
agccgtgtatctccgtgccagcagcttaac
>AF009660|TRBV7-3*03|Homo sapiens|ORF|V-REGION|39374..39663|290 nt|1| | | | |290+0=290| | |
ttacttccaaggcacgggtgcggcagatgactcagggctgcccaaagatcggttctttgc
agtcaggcctgagggatccgtctctactctgaagatccagcgcacagagcagggggactc
agccgcgtatctccgtgccagcagcttaac
>X74843|TRBV7-3*04|Homo sapiens|(F)|V-REGION|140..426|287 nt|1| | || |287+0=287| | |
aatttacttccaaggcacgggtgcggcagatgactcagggctgcccaacgatcggttctt
tgcagtcaggcctgagggatccgtctctactctgaagatccagcgcacagagcgggggga
ctctgccgtgtatctctgtgccagcagctt
>M13550|TRBV7-3*05|Homo sapiens|(F)|V-REGION|1..231|231 nt|1| | | | |231+0=231|partial in 5'| |
ctaatttacttccaaggcacgggtgcggcagatgactcagggctgcccaacgatcggttc
tttgcagtcaggcctgagggatccgtctctactctgaagatccagcgcacagagcggggg
gactcagccgtgtatctctgtgccagcagc
>L36092|TRBV7-4*01|Homo sapiens|F|V-REGION|270051..270340|290 nt|1| | | | |290+0=290| | |
ttactcccagagtgatgctcaacgagacaaatcagggcggcccagtggtcggttctctgc
agagaggcctgagagatccgtctccactctgaagatccagcgcacagagcagggggactc
agctgtgtatctctgtgccagcagcttagc
>L36092|TRBV7-6*01|Homo sapiens|F|V-REGION|307097..307386|290 nt|1| | | | |290+0=290| | |
ttacttcaattatgaagcccaacaagacaaatcagggctgcccaatgatcggttctctgc
agagaggcctgagggatccatctccactctgacgatccagcgcacagagcagcgggactc
ggccatgtatcgctgtgccagcagcttagc
>X58806|TRBV7-6*02|Homo sapiens|(F)|V-REGION|67..351|285 nt|1| | | | |285+0=285| | |
ctgacttacttcaattatgaagcccaacaagacaaatcagggctgcccaatgatcggttc
tctgcagagaggcctgagggatccatctccactctgacgatccagcgcacagagcagcgg
gactcggccatgtatcgctgtgccagcagc
>L36092|TRBV7-7*01|Homo sapiens|F|V-REGION|326549..326838|290 nt|1| | | | |290+0=290| | |
ttacttcaattatgaagctcaaccagacaaatcagggctgcccagtgatcggttctctgc
agagaggcctgagggatccatctccactctgacgattcagcgcacagagcagcgggactc
agccatgtatcgctgtgccagcagcttagc
>X57607|TRBV7-7*02|Homo sapiens|(F)|V-REGION|4..288|285 nt|1| | | | |285+0=285| | |
ctgacttacttcaattatgaagctcaaccagacaaatcagggctgcccagtgatcggttc
tctgcagagaggcctgagggatccatctccactctgacgattcagcgcacagagcagcgg
gactcagccatgtatcgctgtgccagcagc
>M11953|TRBV7-8*01|Homo sapiens|F|V-REGION|215..504|290 nt|1| | | | |290+0=290| | |
ttatttccagaatgaagctcaactagacaaatcggggctgcccagtgatcgcttctttgc
agaaaggcctgagggatccgtctccactctgaagatccagcgcacacagcaggaggactc
cgccgtgtatctctgtgccagcagcttagc
>X61441|TRBV7-8*02|Homo sapiens|F|V-REGION|497..786|290 nt|1| | | | |290+0=290| | |
ttatttccagaatgaagctcaactagacaaatcggggctgcccagtgatcgcttctttgc
agaaaggcctgagggatccgtctccactctgaagatccagcgcacacagaaggaggactc
cgccgtgtatctctgtgccagcagcttagc
>M27384|TRBV7-8*03|Homo sapiens|(F)|V-REGION|25..312|288 nt|1| | | | |288+0=288| | |
acttatttccagaatgaagctcaactagacaaatcggggctgcccagtgatcgcttcttt
gcagaaaggcctgagggatccgtctccactctgaagatccagcgcacacagcaggaggac
tccgccgtgtatctctgtgccagcagccga
>L36092|TRBV7-9*01|Homo sapiens|F|V-REGION|364320..364609|290 nt|1| | | | |290+0=290| | |
ttacttccagaatgaagctcaactagaaaaatcaaggctgctcagtgatcggttctctgc
agagaggcctaagggatctttctccaccttggagatccagcgcacagagcagggggactc
ggccatgtatctctgtgccagcagcttagc
>M15564|TRBV7-9*02|Homo sapiens|(F)|V-REGION|88..377|290 nt|1| | || |290+0=290| | |
ttacttccagaatgaagctcaactagaaaaatcaaggctgctcagtgatcggttctctgc
agagaggcctaagggatctttctccaccttggagatccagcgcacagagcagggggactc
ggccatgtatctctgtgccagcagcttagc
>AF009663|TRBV7-9*03|Homo sapiens|F|V-REGION|108963..109252|290 nt|1| | || |290+0=290| | |
ttacttccagaatgaagctcaactagaaaaatcaaggctgctcagtgatcggttctctgc
agagaggcctaagggatctttctccaccttggagatccagcgcacagagcagggggactc
ggccatgtatctctgtgccagcagcttagc
>M14261|TRBV7-9*04|Homo sapiens|(F)|V-REGION|58..342|285 nt|1| | || |285+0=285| | |
ctgacttacttccagaatgaagctcaactggaaaaatcagggctgctcagtgatcggatc
tctgcagagaggcctaagggatctttctccaccttggagatccagcgcacagagcagggg
gactcggccatgtatctctgtgccagcagc
>M27385|TRBV7-9*05|Homo sapiens|(F)|V-REGION|34..321|288 nt|1| | | | |288+0=288| | |
acttacttccagaatgaagctcaactagaaaaatcaaggctgctcagtgatcggttctct
gcagagaggcctaagggatctctctccaccttggagatccagcgcacagagcagggggac
tcggccatgtatctctgtgccagcaccaaa
>X74844|TRBV7-9*06|Homo sapiens|(F)|V-REGION|100..387|288 nt|1| | | | |288+0=288| | |
acttacttccagaatgaagctcaactagaaaaatcaaggctgctcagtgatcggttctct
gcagagaggcctaagggatctctttccaccttggagatccagcgcacagagcagggggac
tcggccatgtatctctgtgccagcacgttg
>L14854|TRBV7-9*07|Homo sapiens|(F)|V-REGION|1..203|203 nt|1| | || |203+0=203|partial in 5'| |
gacttacttccagaatgaagctcaactagaaaaatcaaggctgctcagtgatcggttctc
tgcagagaggcctaagggatctttctccaccttggagatccagcgcacagaggaggggga
ctcggccatgtatctctgtgccagcagcag
>L36092|TRBV9*01|Homo sapiens|F|V-REGION|206836..207121|286 nt|1| | | | |286+0=286| | |
tcattcagtattataatggagaagagagagcaaaaggaaacattcttgaacgattctccg
cacaacagttccctgacttgcactctgaactaaacctgagctctctggagctgggggact
cagctttgtatttctgtgccagcagcgtag
>AF009660|TRBV9*02|Homo sapiens|F|V-REGION|46949..47234|286 nt|1| | | | |286+0=286| | |
tcattcactattataatggagaagagagagcaaaaggaaacattcttgaacgattctccg
cacaacagttccctgacttgcactctgaactaaacctgagctctctggagctgggggact
cagctttgtatttctgtgccagcagcgtag
>M27380|TRBV9*03|Homo sapiens|(F)|V-REGION|31..312|282 nt|1| | | | |282+0=282| | |
ttcctcattcaatattataatggagaagagagagcaaaaggaaacattcttgaacgattc
tccgcacaacagttccctgacttgcactctgaactaaacctgagctctctggagctgggg
gactcagctttgtatttctgtgccagcagc
